default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] || "db" %>

development:
  <<: *default
  database: strollnsmile_development

test:
  <<: *default
  database: strollnsmile_test

production:
  <<: *default
  database: strollnsmile_production
